BASIC_MODEL:
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "doubao-1.5-pro-32k-250115"
  api_key: 4ceb330a-10bc-4c7a-b729-0bac36c52c25
  # verify_ssl: true
  # max_retries: 3
  # platform: "google_aistudio"
  # platform: "google_aistudio"
  # token_limit: 100000

REASONING_MODEL:

VISION_MODEL:

REACT_FASTCHAT_MODEL:
  base_url: "http://localhost:8000/v1"
  model: "CodeQwen15-7B-Chat"
  api_key: empty
  temperature: 0.9
  top_p: 0.9
  max_tokens: 8192
  stop: ["\n"]

  # verify_ssl: True
  # max_retries: 3

# 搜索引擎配置
SEARCH_ENGINE:
  include_raw_content: True
  include_images: True
  include_image_descriptions: True
